# Generated by Django 3.2.6 on 2022-02-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0006_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
