# Generated by Django 3.2.6 on 2022-02-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0007_rename_name_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.FloatField(),
        ),
    ]
