# Generated by Django 3.2.6 on 2022-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0009_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
