# Generated by Django 3.2.6 on 2022-05-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0011_remove_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='img', upload_to='images'),
        ),
    ]
